### ISSUE TITLE
Not authorized

### ISSUE THREAD

**Issue by sallespro** [respoke/asterisk-chan-respoke-app#1]
hello,

 i am interested in the use of Respoke to connect browser webRTC audio only with local Asterisk SIP peers.

how can i “trunk” my local Asterisk with chn_respoke & everything with Respoke App ?

what am i possibly missing ? the output is :

`offer could not be sent Error: Not authorized. (post /v1/signaling) [Request-Id: 741d3a3c-6960-4ba9-ae2b-874ec040694b`

thank you !

rafael

**Comment by chadxz** [comment]
Hi Rafael. We're excited you're trying out Respoke! The example in this repo uses the `startPhoneCall` method of Respoke, which requires "PSTN Gateway" access to be enabled on your account, and a DID to be provisioned to your account that you can use as your callerId. 

All of these are "beta preview" features, and thus we'll need to enable them on your account.

Please email support@respoke.io to request access to these features and include the email that you used to signup, and we can look into this for you. Also please include a detailed description of your use case, so that we can make sure to get you going in the right direction.

**Comment by sallespro** [comment]
hi chad, thanks for the incentive. what can know about https://docs.respoke.io/client/asterisk/api.html

**Comment by chadxz** [comment]
I'm sorry, I don't understand your question

**Comment by sallespro** [comment]
how can we have access to channel_respoke docs

**Comment by chadxz** [comment]
Ah! You can see the readme for chan_respoke here: https://github.com/respoke/chan_respoke and the getting started guide for chan_respoke is pretty good, too: https://docs.respoke.io/client/asterisk/getting-started.html

Unfortunately I don't think there's a technical API guide for chan_respoke at this time.

**Comment by sallespro** [comment]
i see, i suggest to include a mention to the permission request in the readme for the time being.

**Comment by chadxz** [comment]
You can use chan_respoke without any special permissions on your account. You would just need your own asterisk server. 

`startPhoneCall()` is different, though. It uses our "PSTN Gateway" feature, which is essentially asterisk + chan_respoke hosted in the Respoke infrastructure, combined with Digium Cloud Services to provide DID numbers and outbound PSTN calling.

Perhaps it is confusing that this project is linked in the chan_respoke docs, when it is actually an example of our PSTN Gateway functionality. I think moving it to the correct section of our docs would make things clearer.

**Comment by sallespro** [comment]
i am using the provided configs in https://docs.respoke.io/client/asterisk/getting-started.html

the code snippet below and still i get not authorized.

```
$("#click2call").click(function (){
    // Click To call    

    var client = respoke.createClient({
        endpointId: "bob",
             appId: 'xxxxxx',
             developmentMode: true
    });

    console.log(client);

client.connect({
    onSuccess: function () {
        // call Asterisk
        client.startAudioCall({
            endpointId: "sales"
        });
    }
});
```

```
This appears to be Chrome
(index):46 Object {className: "respoke.Client", endpointId: "bob", connectTries: 0, calls: Array[0], presence: "unavailable"}
signalingChannel.js:2262 XHR finished loading: POST "https://api.respoke.io/v1/tokens".call @ signalingChannel.js:2262that.getToken @ signalingChannel.js:374(anonymous function) @ signalingChannel.js:330Promise.apply @ q.js:1151Promise.promise.promiseDispatch @ q.js:774(anonymous function) @ q.js:1377runSingle @ q.js:123flush @ q.js:111
signalingChannel.js:2262 XHR finished loading: POST "https://api.respoke.io/v1/session-tokens".call @ signalingChannel.js:2262doOpen @ signalingChannel.js:416(anonymous function) @ signalingChannel.js:338_fulfilled @ q.js:820self.promiseDispatch.done @ q.js:849Promise.promise.promiseDispatch @ q.js:782(anonymous function) @ q.js:590runSingle @ q.js:123flush @ q.js:111
socket.io.js:1659 XHR finished loading: GET "https://api.respoke.io/socket.io/1/?__sails_io_sdk_version=0.10.0&app-token…FFEA-4296-A3FC-17B4E6CAF924&Respoke-SDK=Respoke.js/v1.50.0&t=1444944978479".Socket.handshake @ socket.io.js:1659Socket.connect @ socket.io.js:1699Socket @ socket.io.js:1551io.connect @ socket.io.js:94that.authenticate @ signalingChannel.js:1901(anonymous function) @ client.js:408_fulfilled @ q.js:820self.promiseDispatch.done @ q.js:849Promise.promise.promiseDispatch @ q.js:782(anonymous function) @ q.js:590runSingle @ q.js:123flush @ q.js:111
call.js:137 [Respoke] Creating call. id='2DA989F3-DEAB-4A31-994E-0B311B59AD98'
event.js:150 Not adding duplicate listener to stats (evt){that.fire("stats",{stats:evt.stats})}
event.js:150 Not adding duplicate listener to stats (evt){that.fire("stats",{stats:evt.stats})}
localMedia.js:308 getUserMedia() is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
peerConnection.js:774 Negotiation needed.
peerConnection.js:825 offer could not be sent Error: Not authorized. (post /v1/signaling) [Request-Id: 9afdcc95-7248-4415-82f9-c37815bb8bd8](…)signalOffer.onError @ peerConnection.js:825_rejected @ q.js:830(anonymous function) @ q.js:856Promise.when @ q.js:1108Promise.promise.promiseDispatch @ q.js:774(anonymous function) @ q.js:590runSingle @ q.js:123flush @ q.js:111
```

**Comment by chadxz** [comment]
right, you're going to get Not Authorized because startAudioCall is a PSTN Gateway feature, not for interop-ing with your own chan_respoke instance.

**Comment by sallespro** [comment]
how can i dial through my own Asterisk platform, i.e. own chan_respoke instance ?

**Comment by chadxz** [comment]
oh, oops, I misread your code. start**Audio**Call is the correct method. start**Phone**Call is the one that requires special privileges. Let me look again at your problem.

**Comment by chadxz** [comment]
@sallespro from my first pass at debugging your issue, it looks like the code that is resulting in the console log messages you pasted is still using **startPhoneCall**.

I'd be happy to continue to help you resolve the problem that you're having. Could you perhaps send a link to your application or the source you are trying to use to support@respoke.io so that we can track your issue from there? This ticket is probably not the right place to do this. 

Thanks :)

**Comment by sallespro** [comment]
no problem, it would be nice to have a chat room for that purpose.
i can confirm the code is using startAudioCall.

the error message now is 
`caller's receive answer timer expired.`

question how is SIP auth handled in this PJSIP config as it is not included in the example, does it have to be empty ?

**Comment by chadxz** [comment]
The error you are encountering is because your web client is not ever receiving an answer, which could mean that you are calling the wrong endpoint, or because your chan_respoke endpoint is not setup correctly or configured to answer the call or forward it to an entity (i.e. sip phone) that can answer it.

I just setup an irc channel you can use to chat with us if you'd like. irc.freenode.net:6667 #respoke. You can chat with us on the freenode webchat if you don't have an irc client: https://webchat.freenode.net/

We may not keep that channel of communication long-term, but for now a couple of us are on there if you wanna talk about your app and get help. I can't guarantee response time, but we'll try to help you out.
